example:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: feda
    username: root
    password: Aa123456!
  redis:
    host: localhost
    port: 6379
#    password: "123456"
    #database: 0
  mail:
    host: smtp.qq.com
    port: 587
    username: 1009216181@qq.com
    password: hiuijfuvcqegbbef
