example:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: feda
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    password: "Aa123456!"
    database: 0
